name: logcat_example
description: Example flutter app for logcat plugin
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  logcat:
    path: ../

flutter:
  uses-material-design: true

